version: '3.7'
services:
    db:
        image: macochave/meut-db
        container_name: db
        restart: always
        env_file:
            - db/.env
        networks:
            - ut_net:
              ipv4_address: 182.18.7.5
        ports:
            - '3306:3306'
        volumes:
            - db:/var/lib/mysql
    api:
        image: macochave/meut-api
        container_name: api
        restart: always
        volumes:
            - api:/app/node_modules
        ports:
            - '5000:5000'
        networks:
            - ut_net:
              ipv4_address: 182.18.7.10
        env_file:
            - api/.env
        depends_on:
            - db
    web:
        stdin_open: true
        image: macochave/meut-web
        container_name: web
        restart: always
        volumes:
            - web:/app/node_modules
        ports:
            - '4173:4173'
        networks:
            - ut_net:
              ipv4_address: 182.18.7.15
        env_file:
            - web/.env
        depends_on:
            - api
volumes:
    db:
    api:
    web:
networks:
    ut_net:
        ipam:
            driver: default
            config:
                - subnet: 182.18.7.0/24
