version: '3.7'
services:
    # db:
    #     image: macochave/meut-db:local
    #     container_name: db
    #     restart: always
    #     env_file:
    #         - apps/db/.env.development.local
    #     networks:
    #         ut_net:
    #             ipv4_address: 182.18.7.5
    #     ports:
    #         - '3300:3306'
    #     volumes:
    #         - db:/var/lib/mysql
    api:
        image: ghcr.io/macochave/meut-api:dev
        container_name: api
        # restart: always
        volumes:
            - api:/app/node_modules
        ports:
            - '3000:3000'
        networks:
            ut_net:
                ipv4_address: 182.18.7.10
        env_file:
            - apps/server/.env.development.local
        # depends_on:
        #     - db
    web:
        stdin_open: true
        image: ghcr.io/macochave/meut-web:dev
        container_name: web
        # restart: always
        volumes:
            - web:/app/node_modules
        ports:
            - '80:80'
        networks:
            ut_net:
                ipv4_address: 182.18.7.15
        # env_file:
        #     - apps/web/.env.development.local
        depends_on:
            - api
volumes:
    # db:
    api:
    web:
networks:
    ut_net:
        ipam:
            driver: default
            config:
                - subnet: 182.18.7.0/24
