const SQL_OPERATORS = {
	EQ: '=',
	NE: '!=',
	GT: '>',
	GTE: '>=',
	LT: '<',
	LTE: '<=',
	IN: 'IN',
	NIN: 'NOT IN',
	LIKE: 'LIKE',
	NLIKE: 'NOT LIKE',
	ILIKE: 'ILIKE',
	NILIKE: 'NOT ILIKE',
	BETWEEN: 'BETWEEN',
	NBETWEEN: 'NOT BETWEEN',
	IS: 'IS',
	NIS: 'IS NOT',
	AND: 'AND',
	OR: 'OR',
	NOT: 'NOT',
	JSON_CONTAINS: 'JSON_CONTAINS',
};
