export type ReviewType = {
	id_revision: number;
	estado: string;
	detalle: string;
	estacion: number;
	ruta_dictamen: string;
	fecha: string;
	id_tutor: number;
	titulo: string;
	ruta_perfil: string;
	ruta_tesis: string;
	ruta_asesor: string;
	ruta_certificado: string;
	fecha_creacion: string;
	fecha_modificacion: string;
	id_usuario: number;
	nombre: string;
	id_horario: number;
	id_jornada: number;
};
