export const URL = {
	ASSIGNMENT: '/api/assignment',
	AUTH: {
		LOGIN: '/api/auth/login',
		LOGUP: '/api/auth/logup',
		PROFILE: '/api/auth/profile',
		VERIFY: '/api/auth/verified-email',
	},
	COURSE: {
		_: '/api/course',
		ASIGNACION: '/api/course/assignment',
	},
	COURSE_TUTOR: '/api/course_tutor',
	GENERIC: '/api/generic',
	NOTIFICATION: '/api/messaging',
	MESSAGE: '/api/message',
	CHAT: '/api/chat',
	MAILING: '/api/mailing',
	PERIOD: '/api/period',
	PERMISSION: '/api/permission',
	PROFESOR: '/api/profesor',
	PDF: '/api/pdf',
	REVIEW: '/api/review',
	ROL: '/api/rol',
	SCHEDULE: '/api/schedule',
	STORAGE: {
		_: '/api/storage',
		DRAFT: '/api/storage/draft',
		THESIS: '/api/storage/thesis',
		DICTAMEN: '/api/storage/dictamen',
	},
	STUDENT: '/api/student',
	THESIS: '/api/thesis',
	USER_ROL: '/api/user_rol',
	USER: '/api/user',
};
