name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 14

            - name: Change directory web folder
              run: cd web/

            - name: Show current folder path
              run: pwd

            - name: Install dependencies
              run: npm i

            - name: Build for production
              run: npm run build

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ env.GITHUB_TOKEN }}
                  publish_dir: ./dist
