name: devops

on:
    push:
        branches: ['main', 'develop']
    pull_request:
        branches: ['main', 'develop']

jobs:
    docker-images:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v2

            - name: Login to GitHub Container
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.CD_TOKEN }}

            - name: Get image tag name
              run: echo "TAG_NAME=$(if [ $GITHUB_REF == 'refs/heads/main' ]; then echo 'prod'; elif [ $GITHUB_REF == 'refs/heads/develop' ]; then echo 'dev'; else echo 'test'; fi)" >> $GITHUB_ENV

            - name: Build the meut-api Docker image
              run: |
                  docker build -t ghcr.io/macochave/meut-api:${{ env.TAG_NAME }} -f apps/server/Dockerfile .  
                  docker push ghcr.io/macochave/meut-api:${{ env.TAG_NAME }}

            - name: Build the meut-web Docker image
              run: |
                  docker build -t ghcr.io/macochave/meut-web:${{ env.TAG_NAME }} -f apps/web/Dockerfile .  
                  docker push ghcr.io/macochave/meut-web:${{ env.TAG_NAME }}

    # deploy:
    #   needs: docker-images
    #   runs-on: ubuntu-latest
    #   steps:
    #     - name: Install sshpass
    #       run: sudo apt-get install -y sshpass

    #     - name: SSH into Server
    #       run: |
    #         sshpass -p ${{secrets.AUTH_PASS}} ssh -o StrictHostKeyChecking=no ${{secrets.AUTH_SERVER}} << EOF
    #           cd /root/unidad-tesis/
    #           docker login ghcr.io -u macochave -p ${{secrets.CD_TOKEN}}
    #           docker pull ghcr.io/macochave/meut-api:prod
    #           docker pull ghcr.io/macochave/meut-web:prod
    #           docker run -d \
    #             --name meut-api \
    #             -p 5000:5000 \
    #             ghcr.io/macochave/meut-api:prod
    #         EOF
