name: Build and Deploy Docker Images

on: 
  push:
      branches: [ develop ]
  pull_request:
      branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      -name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.8.1'
      
      - name: Install Dependencies of apps/server
        run: npm install
        working-directory: ./apps/server
      
      - name: Build App of apps/server
        run: npm run build
        working-directory: ./apps/server
      
      - name: Install Dependencies of apps/web
        run: npm install
        working-directory: ./apps/web
      
      - name: Build App of apps/web
        run: npm run build
        working-directory: ./apps/web
  
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image of apps/server
        uses: docker/build-push-action@v2
        with:
          context: ./apps/server
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/meut-api:latest
      
      - name: Build and Push Docker Image of apps/web
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        uses: docker/build-push-action@v2
        with:
          context: ./apps/web
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/meut-web:latest